### ISSUE TITLE
Create Custom Live2D

### ISSUE THREAD

**Issue by IRedDragonICY** [IRedDragonICY/vixevia#1]

**Comment by Phoenix1504e** [comment]
do you need any help with this, although I don't have much experience but I will be happy to help if needed

**Comment by IRedDragonICY** [comment]
@Phoenix1504e

Thank you for offering to help, Phoenix1504e. Your willingness to contribute is greatly appreciated.

I understand that you may not have much experience, but any assistance you can provide would be beneficial. As you mentioned, this project is currently unfunded, so I'm unable to provide financial compensation. However, I would be more than happy to acknowledge your contribution in the project's readme.md file, giving you full credit for your work on the Live2D model.

If you're still interested in collaborating, please let me know. We can discuss more about the specific details and requirements of the Live2D model. Thanks again for your offer to help.

**Comment by Phoenix1504e** [comment]
@IRedDragonICY 

Thanks for the reply and just giving me credit would be more than enough and I would love to help in whatever way I can.

And yes I would like to help

**Comment by IRedDragonICY** [comment]
@Phoenix1504e

Thank you for your enthusiasm and willingness to help, Phoenix1504e.
Regarding the Live2D model, I am thrilled to hear your interest in developing the character of Vixevia. Here are some of the characteristics that I envision for her:

- She should have a kawaii and cute anime style.
- She has short to medium length white hair.
- She wears a jacket.
- Her eyes are cyan blue.
- Her skin is fair and beautiful.
- a feminine character.
- For the design inspiration, you may refer to characters like Vestia Zeta, Nakiri Ayame, Shirakami Fubuki, or others of that type.

Please feel free to make the model as complex as you wish. However, if simplicity is more manageable, that's perfectly fine too. The primary goal is to create an "original" character. There's no strict deadline, so take your time and enjoy the creative process.

Thank you so much for your willingness to contribute to this project. I apologize if this request imposes on you in any way, but your help is greatly appreciated. Looking forward to seeing your creation!

**Comment by Phoenix1504e** [comment]
@IRedDragonICY 

Thanks or the specifications, I will try to do it as soon as I can. Will share the samples in couple of days

**Comment by Phoenix1504e** [comment]
I'm sorry I had exams and after that I forgot about this

**Comment by IRedDragonICY** [comment]
That's okay, I have create myself.
