### ISSUE TITLE
How To Talk to Ai

### ISSUE THREAD

**Issue by qwertyuiop1923** [IRedDragonICY/vixevia#5]
**Is your feature request related to a problem? Please describe.**
I installed it and got it running, but I don't know how to talk to Ai.
**Describe the solution you'd like**
Please Add How to Use Tutorial Video
**Describe alternatives you've considered**
Add How to Use Tutorial Video
Add How to Use Tutorial Video
**Additional context**
Add How to Use Tutorial Video

**Comment by IRedDragonICY** [comment]
I apologize for the delay in responding. Currently, there isn’t a tutorial video available, but I’ll work on making the program more _user-friendly_ so that it can be easily run. If you have any further questions, feel free to ask! ヾ(•ω•`)o

**Comment by IRedDragonICY** [comment]
if you have any question, you can open these issues again. :)
